### ISSUE TITLE
Doesnt work with latest cucumber

### ISSUE THREAD

**Issue by gd46** [sebsorin/cucumber-chai-wd#1]
Please update to work with latest cucumber, I get an error saying that the number of arguments dont match up correctly.

**Comment by sebsorin** [comment]
Correct, new cucumber was testing for args number, correction was made using util-arity to set number of args to the declared number of args of the wrapped function

**Comment by gd46** [comment]
Thank you so much for updating this I'll give it a try soon and let you know how it goes
